### ISSUE TITLE
Linked projects instead of dependencies?

### ISSUE THREAD

**Issue by aadrian** [JFormDesigner/markdown-writer-fx#24]
Hi,

Is there a use for Flowless and RichTextFX to be linked and not specified as dependencies in Gradle?

Thank you.

**Comment by JFormDesigner** [comment]
Yes, for bug fixes.

Flowless submodule was necessary because at that time, there was no release for a bug fix. In the mean time Flowless 0.5.2 has been released, so we could remove this submodule easily.

In RichTextFX I've fixed a bug. I've also submitted a PR to fix the bug in RichTextFX, which has been merged. But currently I don't want to upgrade to latest RichTextFX release because there were lot of changes in RichTextFX (which I've not yet tested) and because of this bug https://github.com/TomasMikula/RichTextFX/issues/423. When this bug is fixed, I'll try to upgrade RichTextFX.

**Comment by aadrian** [comment]
@JFormDesigner Thank you for the explanation.
For unpublished (to maven repos) sources, there's this project https://jitpack.io/ that allows projects to be seen as "published" - quite handy.

**Comment by aadrian** [comment]
https://github.com/JFormDesigner/markdown-writer-fx/pull/29

**Comment by JFormDesigner** [comment]
closing because no longer using submodules
