### ISSUE TITLE
Pluggable Markdown conversion API

### ISSUE THREAD

**Issue by DaveJarvis** [JFormDesigner/markdown-writer-fx#6]
The code base is tightly-coupled to the pegdown processor. This is problematic if a faster and less buggy Markdown renderer is desired as a replacement.

See also: http://vladsch.com/blog/15

Recommend adding an interface for the Markdown processor to decouple the specific processor from the application. Replacing the processor should be a matter of re-implementing the interface.

**Comment by JFormDesigner** [comment]
Thanks for the suggestion. I've have worked since a while on replacing pegdown with flexmark-java and commonmark-java on another branch, which I've merged into master about a week ago (and released in version 0.3).

flexmark-java is now always used in the editor for syntax highlighting because it provides source positions in its AST. The preview can use commonmark-java or flexmark-java, switchable in the toolbar. pegmark is no longer supported.

It's not possible to decouple flexmark-java from the **editor** because its AST is required for syntax highlighting and for future smart editing features.

In the **preview** it is now possible to use different processors. See interface `MarkdownPreviewPane.Renderer` and implementations for commonmark-java and flexmark-java:
https://github.com/JFormDesigner/markdown-writer-fx/blob/master/src/main/java/org/markdownwriterfx/preview/MarkdownPreviewPane.java#L59-L63

There is also an experimental implementation of an "GitHub" preview renderer, which sends markdown text to the GitHub Server API and receives HTML. See `github-renderer` branch:
https://github.com/JFormDesigner/markdown-writer-fx/commits/github-renderer

**Comment by DaveJarvis** [comment]
> It's not possible to decouple flexmark-java from the editor because its AST is required for syntax highlighting and for future smart editing features.

It's possible, but probably not worth the effort. :-)

Thanks for making the code more modular!

**Comment by DaveJarvis** [comment]
Looks like the code base is migrating to Flexmark.
